import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Open_Sans } from "next/font/google";

const Sans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mageshkannan Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(Sans.className, "antialiased")}>
          <Navbar />

          {children}
      </body>
    </html>
  );
}
